# Generated by Django 5.0.1 on 2024-01-21 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('endpoints', '0002_flight_alter_abtest_id_alter_endpoint_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Flight',
        ),
    ]
