# Generated by Django 5.0.1 on 2024-01-21 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endpoints', '0004_flight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='arrival_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='flight',
            name='departure',
            field=models.CharField(choices=[('Bucuresti', 'Bucuresti'), ('Iasi', 'Iasi'), ('Cluj', 'Cluj')], max_length=128),
        ),
        migrations.AlterField(
            model_name='flight',
            name='destination',
            field=models.CharField(choices=[('Istanbul', 'Istanbul'), ('Londra', 'Londra'), ('Paris', 'Paris'), ('Amsterdam', 'Amsterdam'), ('Madrid', 'Madrid'), ('Frankfurt', 'Frankfurt'), ('Barcelona', 'Barcelona'), ('Munich', 'Munich'), ('Roma', 'Roma'), ('Lisabona', 'Lisabona'), ('Dublin', 'Dublin'), ('Viena', 'Viena'), ('Manchester', 'Manchester'), ('Atena', 'Atena'), ('Zurich', 'Zurich'), ('Oslo', 'Oslo'), ('Copenhaga', 'Copenhaga'), ('Milano', 'Milano'), ('Berlin', 'Berlin'), ('Bruxelles', 'Bruxelles')], max_length=128),
        ),
    ]
