# Generated by Django 5.0.1 on 2024-02-01 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('endpoints', '0006_delete_abtest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Flight',
        ),
    ]
