# Generated by Django 5.0.1 on 2024-01-21 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endpoints', '0003_delete_flight'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure', models.CharField(choices=[('Bucharest', 'Bucharest'), ('Iasi', 'Iasi')], max_length=128)),
                ('destination', models.CharField(max_length=128)),
                ('flight_date', models.DateField()),
                ('arrival_date', models.DateField(blank=True)),
            ],
        ),
    ]
