# Generated by Django 5.0.1 on 2024-02-01 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('endpoints', '0005_alter_flight_arrival_date_alter_flight_departure_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mlalgorithm',
            name='parent_endpoint',
        ),
        migrations.RemoveField(
            model_name='mlalgorithmstatus',
            name='parent_mlalgorithm',
        ),
        migrations.RemoveField(
            model_name='mlrequest',
            name='parent_mlalgorithm',
        ),
        migrations.DeleteModel(
            name='ABTest',
        ),
        migrations.DeleteModel(
            name='MLAlgorithmStatus',
        ),
        migrations.DeleteModel(
            name='MLAlgorithm',
        ),
        migrations.DeleteModel(
            name='MLRequest',
        ),
    ]
